/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CsvToJsonRouteImport } from './routes/csv-to-json'
import { Route as CsvComparatorRouteImport } from './routes/csv-comparator'
import { Route as IndexRouteImport } from './routes/index'

const CsvToJsonRoute = CsvToJsonRouteImport.update({
  id: '/csv-to-json',
  path: '/csv-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvComparatorRoute = CsvComparatorRouteImport.update({
  id: '/csv-comparator',
  path: '/csv-comparator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csv-comparator': typeof CsvComparatorRoute
  '/csv-to-json': typeof CsvToJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csv-comparator': typeof CsvComparatorRoute
  '/csv-to-json': typeof CsvToJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csv-comparator': typeof CsvComparatorRoute
  '/csv-to-json': typeof CsvToJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csv-comparator' | '/csv-to-json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csv-comparator' | '/csv-to-json'
  id: '__root__' | '/' | '/csv-comparator' | '/csv-to-json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsvComparatorRoute: typeof CsvComparatorRoute
  CsvToJsonRoute: typeof CsvToJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/csv-to-json': {
      id: '/csv-to-json'
      path: '/csv-to-json'
      fullPath: '/csv-to-json'
      preLoaderRoute: typeof CsvToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-comparator': {
      id: '/csv-comparator'
      path: '/csv-comparator'
      fullPath: '/csv-comparator'
      preLoaderRoute: typeof CsvComparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsvComparatorRoute: CsvComparatorRoute,
  CsvToJsonRoute: CsvToJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
